[package]
name = "collectors"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "collectors"
path = "src/main.rs"

[dependencies]
chassis = { version = "0.1.0", path = "../chassis" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
